config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'books#index'
  resources :books 
  resources :authors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord

  has_many :authorships
  has_many :books, through: :authorships

  def full_name
    "#{self.first_name} #{self.last_name}"  
  end

end

app/models/authorship.rb
class Authorship < ApplicationRecord

  belongs_to :book  
  belongs_to :author

end

app/models/book.rb
class Book < ApplicationRecord

  has_many :authorships
  has_many :authors, through: :authorships

  def author_info
    self.authors
  end

  def self.search(keyword)
    if keyword.present?
      Book.where("title ILIKE ? OR genre ILIKE ? OR classification ILIKE ? OR book_type ILIKE ?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%") 
    else
      Book.all
    end
  end  

  def self.classifications
    [
     'General Works - encyclopedias',
     'Philosophy, Psychology, Religion',
     'History - Auxiliary Sciences',
     'History (except American)',
     'General U.S. History',
     'Local U.S. History',
     'Geography, Anthropology, Recreation',
     'Social Sciences U',
     'Political Science V',
     'Law Z - Bibliography and Library Science',
     'Education',
     'Music',
     'Fine Arts',
     'Language and Literature',
     'Science',
     'Medicine',
     'Agriculture',
     'Technology',
     'Military',
     'Naval Science',
     'Bibliography and Library Science' 
    ]
  end

  def self.book_types
    [
      'Fiction',
      'Nonfiction'
    ]
  end  

  def author_names
    names = ''
    if authors.length > 0
      names = 'by '
    end
    count = 0
    authors.each do |author|
      count += 1
      names += author.full_name
      if authors.length != count 
        names += ', '
      end
    end
    names
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    
    def index
      @authors = Author.all
    end

    def new
      @author = Author.new
    end

    def show
      @author = Author.find(params[:id])
    end

    def create
      @author = Author.create(author_params)
      redirect_to @author, notice: 'Author was successfully created.'
    end

    def edit
      @author = Author.find(params[:id])
    end

    def update
      @author = Author.find(params[:id])
      @author.update_attributes(author_params)
      redirect_to @author, notice: 'Author was successfully updated.'
    end

    def destroy
      @author = Author.find(params[:id])
      @author.destroy
      redirect_back(fallback_location: root_path)
    end
    
    private

    def author_params
      params.require(:author).permit(:first_name, :last_name, :age)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.search(params[:keyword])
  end

  def new
    @book = Book.new
  end
  
  def create
    @book = Book.create(book_params)
    redirect_to root_path
  end

  def show
    @book = Book.find(params[:id])
    @author = Author.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update_attributes(book_params)
    redirect_to root_path
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to root_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :genre, :classification, :book_type, :year)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Edit Your Author Details Here</h1>
  <%= simple_form_for @author do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :age %>
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/authors/index.html.erb
<table class='table'>
  <thread>
    <tr>
      <th scope='col'>Author</th>
      <th scope='col'>Age</th>
    </tr>  
  </thread>
  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= link_to author.full_name, author_path(author) %></td>
        <td><%= author.age %></td>
        <td><%= link_to 'Delete Author', author_path(author), method: :delete, data: {confirm: 'Are you sure you want to delete this author?'} %></td>
        <td><%= link_to 'Edit Author', edit_author_path(author) %></td>
        <td><%= link_to 'Author Details', author_path(author) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/authors/new.html.erb
<div class="booyah-box col-10 offset-1">
  <%= simple_form_for Author.new do |f| %>
    <h3>Add an Author:</h3>
    <br />
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :age %>
    <%= f.submit "Add this Author" %>
  <% end %>
</div>  

app/views/authors/show.html.erb
<h3>Author</h3>

<p>
  <h3>Name:</h3>
  <%= @author.full_name %>
</p>

<p>
  <h3>Age:</h3>
  <%= @author.age %>
</p>

<h3>More Books From This Author</h3>

<% @author.books.each do |book| %>
  <%= link_to book.title, book_path(book) %>
<% end %>

app/views/books/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Edit Your Book Details Here</h1>
  <%= simple_form_for @book do |f| %>
    <%= f.input :title %>
    <%= f.input :genre %>
    <%= f.input :classification %>
    <%= f.input :book_type %>
    <%= f.input :year %>
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/books/index.html.erb
<table class='table'>
  <thread>
    <tr>
      <th scope='col'>Title</th>
      <th scope='col'>Author(s)</th>
      <th scope='col'>Year</th>
    </tr>  
  </thread>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author_names %></td>
        <td><%= book.year %></td>
        <td><%= link_to 'Show', book_path(book) %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book_path(book), method: :delete, data: {confirm: 'Are you sure you want to delete this book?'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h3>Add A Book</h3>
  <%= simple_form_for @book do |f| %>
    <%= f.input :title %>
    <%= f.input :genre %>
    <%= f.input :classification %>
    <%= f.input :book_type %>
    <%= f.input :year %>
    <%= f.submit 'Add this Book' %>
  <% end %>
</div>

app/views/books/show.html.erb
<%= link_to 'Edit', edit_book_path(@book) %>
<%= ' or ' %>
<%= link_to 'Destroy', book_path(@book), method: :delete, data: {confirm: 'Are you sure you want to delete this book?'} %>
<%= ' this book' %>
<h1><%= @book.title %></h1>
<h1><%= @book.genre %></h1>
<h1><%= @book.classification %></h1>
<h1><%= @book.book_type %></h1>
<h1><%= @book.year %></h1>
<h3>Author(s) who wrote this book</h3>

<% @book.authors.each do |author| %>
  <%= link_to author.full_name, author_path(author) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FhHomework02</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>

    <div class="booyah-box col-10 ">
      <%= link_to 'Books', root_path, class: 'navbar-brand' %>
    </div>

    <div class="booyah-box col-10 ">
      <%= link_to 'Authors', authors_path, class: 'navbar-brand' %>
    </div>

    <div class="booyah-box col-10 ">
      <%= link_to 'Add Book', new_book_path, class: 'navbar-brand' %>
    </div>

    <div class="booyah-box col-10 ">
      <%= link_to 'Add Author', new_author_path, class: 'navbar-brand' %>
    </div>

    <br/>

    <div class="booyah-box col-10 ">
      <%= form_tag(books_path, method: "get") do %>
        <div>  
          <%= label_tag(:keyword, "Search for a book:") %>
        </div> 
        <%= text_field_tag(:keyword, nil, placeholder: 'Book Info') %>
        <%= submit_tag("Search") %>
      <% end %>
    </div>

    <br/><br/>

    <%= yield %>
  </body>
</html>